---
# tasks file for rabbitmq-cluster

- name: set rabbit conf file (clustering)
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  tags:
    - configuration
    - rabbitmq
    - clustering

- name: ensure cookies are the same between all envs (clustering)
  template:
    src: erlang.cookie.j2
    dest: /var/lib/rabbitmq/.erlang.cookie
  tags:
    - configuration
    - rabbitmq
    - clustering

- name: get server hostnames (clustering)
  ec2_search:
    key: "{{ rabbitmq_ec2_tag_key }}"
    value: "{{ rabbitmq_ec2_tag_value }}"
  environment:
    AWS_ACCESS_KEY_ID: "{{ app_settings['rabbitmq']['aws_access_key_id'] }}"
    AWS_SECRET_ACCESS_KEY: "{{ app_settings['rabbitmq']['aws_secret_access_key'] }}"
  register: nodes

- name: start rabbitmq-server (clustering)
  service:
    name: rabbitmq-server
    state: started
  tags:
    - configuration
    - rabbitmq
    - clustering

- name: turn off rabbitmq but not the erlang process (clustering)
  command: "{{ item }}"
  with_items:
    - rabbitmqctl stop_app
    - rabbitmqctl reset
  tags:
    - configuration
    - rabbitmq
    - clustering

- name: cluster all known nodes (clustering)
  command: "rabbitmqctl join_cluster rabbit@{{ item['hostname'] }}{{ rabbitmq_nodename_suffix }}"
  with_items: "{{ nodes['info']|default([]) }}"
  when: nodes
  ignore_errors: yes

- name: turn back on rabbitmq
  command: rabbitmqctl start_app
  tags:
    - configuration
    - rabbitmq
    - clustering

- name: stop rabbitmq-server (clustering)
  service:
    name: rabbitmq-server
    state: stopped
  tags:
    - configuration
    - rabbitmq
    - clustering
